### ISSUE TITLE
aurelia should replace moment.js with date-fns, saves 10-15kb gzipped. (make it faster)

### ISSUE THREAD

**Issue by loaded02** [gothinkster/aurelia-realworld-example-app#12]

**Comment by loaded02** [comment]
date-fns is not working with cli setup [issue](https://discourse.aurelia.io/t/how-to-import-date-fns-module-via-aurelia-cli/816/3). Any ideas?

**Comment by loaded02** [comment]
aurelia cli and webpack should do it...

**Comment by loaded02** [comment]
Ok I made it work! Date-fns is working with a aurelia-cli setup with webpack as a module loader. Size comparisson of the bundles is: 
* require-js and momentjs 480Kb
* webpack and date-fns 460 Kb [at this branch](https://github.com/loaded02/aurelia-realworld-example-app/tree/webpack)
@vegarringdal what do you think? Is it worth it? There might be optimization potential especially regarding excluding sourcemaps. I am no webpack expert and couldnt get rid of the sourcemaps just now. Might try later.

**Comment by vegarringdal** [comment]
yes, think 20kb is good :-)
is it minified, how much gzipped?

**Comment by loaded02** [comment]
Cool thanks!! Any optimization hints for this pr #33? Could not exclude sourcemaps from beeing generated, but I excluded them from beeing deployed by travis.
