### ISSUE TITLE
favorite buttons on posts on home page isnt working, and displaying green when loaded/is favorite

### ISSUE THREAD

**Issue by loaded02** [gothinkster/aurelia-realworld-example-app#13]

**Comment by loaded02** [comment]
In article-preview.js in function onToggleFavorited() variable this.slug is undefined! Merged in PR #20. Do you want to check on this? @dmytrohridin

**Comment by dmytrohridin** [comment]
@loaded02 I will check it

**Comment by dmytrohridin** [comment]
@loaded02 done
