### ISSUE TITLE
bluebird, remove it to speed up ?

### ISSUE THREAD

**Issue by vegarringdal** [gothinkster/aurelia-realworld-example-app#30]
bluebird, remove it to speed up ?
https://github.com/gothinkster/aurelia-realworld-example-app/blob/master/package.json#L18

any reason to keep this ?

**Comment by loaded02** [comment]
@vegarringdal  We could get rid of it in favor of bundle size, but bluebird is actually a faster Promise library than the default one. As far as I understood it.

**Comment by vegarringdal** [comment]
@loaded02 
That was only in Edge wasn't it?  (maybe I remember wrong)
No one running chrome lighthouse from Edge browser and posting on blogs :-)

**Comment by loaded02** [comment]
@vegarringdal you are right about edge. We should drop it. We are not targeting edge ;)

**Comment by vegarringdal** [comment]
👍 

Great, Im thinking a simple note what needs to be added for support for IE11 is good enough (polyfill for promise and fetch)
