### ISSUE TITLE
aurelia-validation

### ISSUE THREAD

**Issue by vegarringdal** [gothinkster/aurelia-realworld-example-app#31]
`aurelia-validation`, do you need this?
I understand why, but how big is it?
Better to have alt sample how to use this?
Do not think other frameworks are including this,so why not skip it and get the speed so its faster compared to other frameworks.

https://github.com/gothinkster/aurelia-realworld-example-app/blob/master/package.json#L17

**Comment by loaded02** [comment]
@vegarringdal Good point. We should replace it!
