### ISSUE TITLE
Unable to find module with ID upon clicking username

### ISSUE THREAD

**Issue by IsaacHub** [gothinkster/aurelia-realworld-example-app#35]
After I login, I click on my username which appears top right corner, and I got following error in the console:

```
ERROR [app-router] Error: Unable to find module with ID: components/profile/profile-article-component
```
Is this expected or a bug?

One more bug: favicon is not displayed.

**Comment by loaded02** [comment]
Looks like a bug. Route is defined in ```/src/components/profile/profile-component.js```

Favicon also seems like a bug. Thx. If you like commit a pr!

**Comment by dmytrohridin** [comment]
Hi @loaded02. I've fixed this issue. It's currently in opened PR state
