### ISSUE TITLE
Connection between the front and back end

### ISSUE THREAD

**Issue by adriatic** [gothinkster/aurelia-realworld-example-app#9]
This is mostly the documentation issue and it boils down to the following observation: 

I create a local instance of **[Aurelia version of Conduit](https://github.com/gothinkster/aurelia-realworld-example-app)** without a hitch (not too surprising 😏) and without even thinking about its back end, I pointed the browser to http://localhost:9000. Instead of seeing a complaint that I did not provide the back end application, I saw this:

![image](https://user-images.githubusercontent.com/2712405/39087039-51652082-4568-11e8-8037-9269c165b6b4.png)

indicating that my local instance knows how to find a pre-provisioned back end instance, which is being "molested" by everyone.

The point I am trying to make is that the **[README.md](https://github.com/gothinkster/aurelia-realworld-example-app/blob/master/README.md)** file, should have a brief explanation about the **["default" back end  server](https://github.com/gothinkster/aurelia-realworld-example-app/blob/master/src/shared/services/config.js)**.

**Comment by loaded02** [comment]
Would you like to create a PR? Cause I dont really see where you're going with this. Sorry.

**Comment by adriatic** [comment]
Sorry for confusing you - and yes I will make the PR.
